language: java

# Cobertura is not supported in JDK11 so you must downgrade the JDK that Travis uses if you want to use Cobertura with Travis.
# See https://github.com/cobertura/cobertura/issues/381
jdk:
  - openjdk8

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2'

script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - - mvn cobertura:cobertura -Dcobertura.report.format=xml -Dmaven.javadoc.skip.true


after_success:
  - bash <(curl -s https://codecov.io/bash)
